/**
 * Audit/security event names. Security events from AUTH_AUTHORIZATION.md §61; USER_REGISTERED
 * from §7 (step 10). Add new actions here as slices introduce sensitive operations.
 */
export const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  PHONE_VERIFIED: 'PHONE_VERIFIED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',
  // Restaurants (Slice 3)
  RESTAURANT_CREATED: 'RESTAURANT_CREATED',
  RESTAURANT_APPLICATION_SUBMITTED: 'RESTAURANT_APPLICATION_SUBMITTED',
  RESTAURANT_APPROVED: 'RESTAURANT_APPROVED',
  RESTAURANT_REJECTED: 'RESTAURANT_REJECTED',
  RESTAURANT_RESUBMISSION_REQUESTED: 'RESTAURANT_RESUBMISSION_REQUESTED',
  RESTAURANT_STATUS_CHANGED: 'RESTAURANT_STATUS_CHANGED',
  RESTAURANT_SUSPENDED: 'RESTAURANT_SUSPENDED',
  RESTAURANT_SETTINGS_CHANGED: 'RESTAURANT_SETTINGS_CHANGED',
  RESTAURANT_PAYMENT_ACCOUNT_CHANGED: 'RESTAURANT_PAYMENT_ACCOUNT_CHANGED',
  RESTAURANT_STAFF_ADDED: 'RESTAURANT_STAFF_ADDED',
  RESTAURANT_STAFF_UPDATED: 'RESTAURANT_STAFF_UPDATED',
  RESTAURANT_STAFF_REMOVED: 'RESTAURANT_STAFF_REMOVED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  // Payments (Slice 7, PAYMENT_RULES §48)
  PAYMENT_STATUS_CHANGED: 'PAYMENT_STATUS_CHANGED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_STATUS_CHANGED: 'REFUND_STATUS_CHANGED',
  REFUND_DECISION_RECORDED: 'REFUND_DECISION_RECORDED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
