/**
 * Audit/security event names. Security events from AUTH_AUTHORIZATION.md §61; USER_REGISTERED
 * from §7 (step 10). Add new actions here as slices introduce sensitive operations.
 */
export const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  PHONE_VERIFIED: 'PHONE_VERIFIED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',
  MFA_ENABLED: 'MFA_ENABLED',
  MFA_DISABLED: 'MFA_DISABLED',
  MFA_FAILED: 'MFA_FAILED',
  // Admin configuration (API_SPEC §107)
  CONFIGURATION_CHANGED: 'CONFIGURATION_CHANGED',
  DISPATCH_SETTINGS_CHANGED: 'DISPATCH_SETTINGS_CHANGED',
  // Restaurants (Slice 3)
  RESTAURANT_CREATED: 'RESTAURANT_CREATED',
  RESTAURANT_APPLICATION_SUBMITTED: 'RESTAURANT_APPLICATION_SUBMITTED',
  RESTAURANT_APPROVED: 'RESTAURANT_APPROVED',
  RESTAURANT_REJECTED: 'RESTAURANT_REJECTED',
  RESTAURANT_RESUBMISSION_REQUESTED: 'RESTAURANT_RESUBMISSION_REQUESTED',
  RESTAURANT_STATUS_CHANGED: 'RESTAURANT_STATUS_CHANGED',
  RESTAURANT_SUSPENDED: 'RESTAURANT_SUSPENDED',
  RESTAURANT_SETTINGS_CHANGED: 'RESTAURANT_SETTINGS_CHANGED',
  RESTAURANT_PAYMENT_ACCOUNT_CHANGED: 'RESTAURANT_PAYMENT_ACCOUNT_CHANGED',
  RESTAURANT_STAFF_ADDED: 'RESTAURANT_STAFF_ADDED',
  RESTAURANT_STAFF_UPDATED: 'RESTAURANT_STAFF_UPDATED',
  RESTAURANT_STAFF_REMOVED: 'RESTAURANT_STAFF_REMOVED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  // Payments (Slice 7, PAYMENT_RULES §48)
  PAYMENT_STATUS_CHANGED: 'PAYMENT_STATUS_CHANGED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_STATUS_CHANGED: 'REFUND_STATUS_CHANGED',
  REFUND_DECISION_RECORDED: 'REFUND_DECISION_RECORDED',
  // Riders & dispatch (Slices 8–9)
  RIDER_APPROVED: 'RIDER_APPROVED',
  RIDER_REJECTED: 'RIDER_REJECTED',
  RIDER_SUSPENDED: 'RIDER_SUSPENDED',
  RIDER_RESTORED: 'RIDER_RESTORED',
  RIDER_UPDATED: 'RIDER_UPDATED',
  // Risk (RISK_RULES §40–41)
  RISK_EVENT_RECORDED: 'RISK_EVENT_RECORDED',
  RISK_RULE_CREATED: 'RISK_RULE_CREATED',
  RISK_RULE_UPDATED: 'RISK_RULE_UPDATED',
  RISK_FLAG_RESOLVED: 'RISK_FLAG_RESOLVED',
  RISK_FLAG_DISMISSED: 'RISK_FLAG_DISMISSED',
  RISK_RESTRICTION_CREATED: 'RISK_RESTRICTION_CREATED',
  RISK_RESTRICTION_OVERRIDDEN: 'RISK_RESTRICTION_OVERRIDDEN',
  RISK_RESTRICTION_RESOLVED: 'RISK_RESTRICTION_RESOLVED',
  // Promotions (PROMOTION_RULES §54)
  PROMOTION_CREATED: 'PROMOTION_CREATED',
  PROMOTION_UPDATED: 'PROMOTION_UPDATED',
  PROMOTION_DISABLED: 'PROMOTION_DISABLED',
  // Reviews (REVIEW_RULES §36)
  REVIEW_HIDDEN: 'REVIEW_HIDDEN',
  REVIEW_RESTORED: 'REVIEW_RESTORED',
  REVIEW_REMOVED: 'REVIEW_REMOVED',
  REVIEW_RESPONSE_SAVED: 'REVIEW_RESPONSE_SAVED',
  REVIEW_REPORT_RESOLVED: 'REVIEW_REPORT_RESOLVED',
  // Support (SUPPORT_RULES §29)
  SUPPORT_TICKET_ASSIGNED: 'SUPPORT_TICKET_ASSIGNED',
  SUPPORT_TICKET_UPDATED: 'SUPPORT_TICKET_UPDATED',
  SUPPORT_TICKET_RESOLVED: 'SUPPORT_TICKET_RESOLVED',
  SUPPORT_INTERNAL_NOTE_ADDED: 'SUPPORT_INTERNAL_NOTE_ADDED',
  // Financial (FINANCIAL_SPEC §58)
  SETTLEMENT_CREATED: 'SETTLEMENT_CREATED',
  SETTLEMENT_APPROVED: 'SETTLEMENT_APPROVED',
  SETTLEMENT_PROCESSING: 'SETTLEMENT_PROCESSING',
  SETTLEMENT_COMPLETED: 'SETTLEMENT_COMPLETED',
  SETTLEMENT_FAILED: 'SETTLEMENT_FAILED',
  FINANCIAL_ADJUSTMENT_CREATED: 'FINANCIAL_ADJUSTMENT_CREATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
